CREATE TABLE "user" (
    user_id SERIAL PRIMARY KEY,
    email VARCHAR(255),
    username VARCHAR(15) NOT NULL,
    whatsapp_number VARCHAR(12) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);